"""identity-column-add-rewrites — Atlas PG310 equivalent.

ALTER TABLE ... ADD COLUMN <c> <type> GENERATED ALWAYS AS IDENTITY (or
GENERATED BY DEFAULT AS IDENTITY) on a populated table requires a full table
rewrite: Postgres must assign a unique sequence value to every existing row
and write the result. Holds AccessExclusiveLock for the duration.

Atlas PG310 fires only on ALTER (not inline CREATE TABLE). Our state machine
suppresses same-migration tables.
"""

from __future__ import annotations

from collections.abc import Iterator
from typing import Any

from pglast import ast
from pglast.enums import AlterTableType, ConstrType

from ..core.ast_utils import table_name
from ..core.finding import Finding, Severity
from ..core.state import MigrationState, table_known_empty
from ._registry import RuleContext, register_rule

RULE_ID = "identity-column-add-rewrites"


@register_rule(
    id=RULE_ID,
    severity=Severity.CRITICAL,
    applies_to=(ast.AlterTableStmt,),
    doc=(
        "ALTER TABLE ADD COLUMN ... GENERATED [ALWAYS|BY DEFAULT] AS IDENTITY on an "
        "existing table rewrites every row to assign unique sequence values, under "
        "AccessExclusiveLock. Use ADD COLUMN nullable + backfill + ALTER COLUMN ADD "
        "GENERATED ALWAYS AS IDENTITY as a multi-step alternative on large tables. "
        "Matches Atlas PG310."
    ),
)
def check(stmt: Any, state: MigrationState, ctx: RuleContext) -> Iterator[Finding]:
    if not isinstance(stmt, ast.AlterTableStmt):
        return

    table = table_name(stmt.relation)
    if table and table_known_empty(state, table):
        return

    line, column = ctx.line_col()

    for cmd in stmt.cmds or ():
        if not isinstance(cmd, ast.AlterTableCmd):
            continue
        if cmd.subtype != AlterTableType.AT_AddColumn:
            continue
        column_def = cmd.def_
        if not isinstance(column_def, ast.ColumnDef):
            continue
        if not _has_identity_constraint(column_def):
            continue

        col_name = column_def.colname or "<unnamed>"
        yield Finding(
            rule_id=RULE_ID,
            severity=Severity.CRITICAL,
            file=ctx.file,
            line=line,
            column=column,
            message=(
                f"ADD COLUMN {col_name} ... GENERATED AS IDENTITY on "
                f"{table or 'table'} rewrites every row and locks the table for the "
                f"duration."
            ),
            help=(
                "Identity columns require Postgres to assign a unique sequence value "
                "to every existing row, which means a full table rewrite under "
                "AccessExclusiveLock. On large tables this blocks reads and writes "
                "for minutes. The non-blocking alternative: ADD COLUMN nullable, "
                "backfill in batched UPDATEs using nextval('seq_name'), then ALTER "
                "COLUMN ADD GENERATED ALWAYS AS IDENTITY (which is catalog-only)."
            ),
            suggested_fix=(
                f"-- Multi-step pattern:\n"
                f"CREATE SEQUENCE {table}_{col_name}_seq;\n"
                f"ALTER TABLE {table} ADD COLUMN {col_name} bigint;\n"
                f"-- Backfill in batches:\n"
                f"--   UPDATE {table} SET {col_name} = nextval('{table}_{col_name}_seq') "
                f"WHERE {col_name} IS NULL ORDER BY <pk> LIMIT N;\n"
                f"ALTER TABLE {table} ALTER COLUMN {col_name} "
                f"ADD GENERATED ALWAYS AS IDENTITY;"
            ),
        )


def _has_identity_constraint(column_def: ast.ColumnDef) -> bool:
    for constraint in column_def.constraints or ():
        if not isinstance(constraint, ast.Constraint):
            continue
        if constraint.contype == ConstrType.CONSTR_IDENTITY:
            return True
    return False


